# Generated by Django 5.1.3 on 2024-11-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241124_2219'),
    ]

    operations = [
    ]
